### ISSUE TITLE
Redundant OBJC_DISABLE_INITIALIZE_FORK_SAFETY

### ISSUE THREAD

**Issue by yurrriq** [LnL7/nix-darwin#131] opened 2019-03-01 16:30 UTC
I can't seem to build anymore.. and I'm not sure when exactly this happened.

```
error: The unique option `launchd.daemons.nix-daemon.serviceConfig.EnvironmentVariables.OBJC_DISABLE_INITIALIZE_FORK_SAFETY' is defined multiple times, in `/nix/store/d1w67qj5w4ixgmhr983v8hqqd94ilk7h-source/modules/launchd' and `/nix/store/d1w67qj5w4ixgmhr983v8hqqd94ilk7h-source/modules/services/nix-daemon.nix'.
```

I'm using  LnL7/nix-darwin@feaf3718dbe2ab2558f56b900e0b808e60a60814 and NixOS/nixpkgs-channels@aabc61049c011b40ef15c354d7d84c840d6b6a6d at the moment.

**Comment by LnL7** [comment] 2019-03-01 18:58
Fixed by https://github.com/LnL7/nix-darwin/commit/1a3a9d91b461f7e8bda13d0e50ead976cc8a0d1a.

But you don't have to set the environment variable explicitly anymore, nix-darwin will set that by default now until the issue is resolved.

**Closed by LnL7** 2019-03-01 18:58 UTC

**Comment by yurrriq** [comment] 2019-03-03 01:48
Thanks!

**Comment by yurrriq** [comment] 2019-03-06 15:01
Oops: https://github.com/yurrriq/dotfiles/blob/7cddca5398930f16fd969b36c7055dbde4e23562/nix/.config/nixpkgs/machines/srus/configuration.nix#L109-L110
