### ISSUE TITLE
/run/current-system symlink is not created

### ISSUE THREAD

**Issue by SuperSandro2000** [LnL7/nix-darwin#258] opened 2020-11-30 03:01 UTC
I setup nix and then nix-darwin on Mac OS Catalina in a VM with OpenCore 9 and the symlink from ``/run/current-system`` to ``/nix/var/nix/profiles/system`` was not created. I don't really understand it and a couldn't find anything in source that would have helped me debug this any further. After running ``sudo ln -s /nix/var/nix/profiles/system /run/current-system`` everything seems to work like it should.

Maybe this should be added as a fallback in the installer if ``/run/current-system`` is not created by the end of it.

**Comment by hlolli** [comment] 2021-12-01 04:29
+1 I had the same thing happening, and you suggestion fixed it. Happened on Monterey and a lot of strange things about sndbox, dylib and permissions have been happening. So it's a guess difficult to pinpoint the causes for this.

**Comment by Enzime** [comment] 2023-08-02 07:29
Closing this issue as it should be fixed by #687, please leave a comment if you still have any issues.

**Closed by Enzime** 2023-08-02 07:29 UTC
