### ISSUE TITLE
Bash autocompletion causes slow interactive login times

### ISSUE THREAD

**Issue by ElvishJerricco** [LnL7/nix-darwin#101] opened 2018-09-21 23:35 UTC
When I set `programs.bash.enableCompletion = true;`, it adds 0.8s to my login time, regardless of whether the shell is interactive or not. Annoying enough that now I just disable it.

**Comment by LnL7** [comment] 2018-10-08 16:45
I recall something about this related to the fact that the default version of bash on macOS is really old. Using the nix version of bash as your login shell might resolve this if that's the case.

**Comment by ElvishJerricco** [comment] 2018-10-08 18:53
@LnL7 I have:

```nix
{ pkgs, ... }: {
  users.users.will = {
    description = "Will Fancher";
    home = "/Users/will";
    shell = "/run/current-system/sw/bin/bash";
  };
  environment.shells = [ pkgs.bashInteractive ];
}
```

So I thought I had that set up right. And in fact:

```bash
$ echo $BASH
/run/current-system/sw/bin/bash
$ echo $BASH_VERSION
4.4.12(1)-release
```

However, oddly enough, if I do these things directly from SSH then I get different results:

```
$ ssh hostname 'echo $BASH'
/bin/bash
$ ssh hostname 'echo $BASH_VERSION'
4.4.12(1)-release
```

It's using `/bin/bash`, though it does appear to be a recent version.
```

**Comment by LnL7** [comment] 2018-10-17 17:11
With https://github.com/LnL7/nix-darwin/pull/109 non-interactive cases shouldn't suffer from this anymore, but unless that was the cause somehow there's not much that can be done about it I think.

**Comment by ElvishJerricco** [comment] 2018-10-17 17:15
@LnL7 though it's definitely *less* of a problem for only interactive logins to be slow, I think it's still a problem. The issue should probably remain open and be renamed.

**Comment by LnL7** [comment] 2018-10-17 17:17
Oh, I confused this with https://github.com/LnL7/nix-darwin/issues/98.

**Comment by LnL7** [comment] 2018-10-17 20:13
Not sure, that's why my initial suspicion was the default bash 3.2.

**Comment by Kaali** [comment] 2019-12-12 07:11
Pushed a fix for this which speeds up the interactive bash startup time significantly. Bash loads the completions from /share/ on demand, so they don't have to be preloaded. NixOS also fixed this in the same way in https://github.com/NixOS/nixpkgs/pull/32534

**Closed** 2020-01-21 11:21 UTC
