### ISSUE TITLE
Error: brew

### ISSUE THREAD

**Issue by PlumpMath** [LnL7/nix-darwin#492] opened 2022-08-17 05:38 UTC
Installing android-file-transfer
==> Downloading https://dl.google.com/dl/androidjumper/mtp/5071136/androidfiletransfer.dmg
Error: could not find a temporary directory
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:35:in `tmpdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:112:in `tmpdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:120:in `create'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:87:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:146:in `extract_nestedly'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:217:in `extract_primary_container'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:78:in `stage'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:106:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:79:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:78:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:78:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:183:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
==> Installing Cask android-file-transfer
==> Purging files for version 5071136 of Cask android-file-transfer
Installing android-file-transfer has failed!

Homebrew Bundle failed! 1 Brewfile dependency failed to install.

.
Reinstalling directly with brew doesn't give any errors.
like
brew reinstall --cask brew-pkgs

**Comment by malob** [comment] 2022-08-29 18:39
I added `android-file-transfer` to my `homebrew.casks` and it installed without issue, so at present I'm unable to reproduce this.

**Comment by PlumpMath** [comment] 2022-08-31 10:24
Oh, I didn't set the settings.
Is there an option I am missing or am doing wrong?

  homebrew = {
    taps = [ "homebrew/core" "homebrew/cask" "homebrew/cask-versions" ];
    
  brews = [ "bat" ];
  
  casks = [ "android-file-transfer" ];
  
      brewPrefix = if pkgs.stdenv.hostPlatform.isAarch64 then "/opt/homebrew/bin" else "/usr/local/bin";
    enable = true;
    autoUpdate = true;
    cleanup = "zap"; # keep it clean
    global = {
      brewfile = true;
      noLock = true;
    };
};

Thanks.

**Comment by PlumpMath** [comment] 2022-09-06 16:29
homebrew.autoUpdate
homebrew.cleanup
homebrew.global.noLock

As changed today, I removed them all.

**Comment by Enzime** [comment] 2023-07-23 08:56
I'm closing this issue, please comment if you're still having issues

**Closed by Enzime** 2023-07-23 08:56 UTC
