### ISSUE TITLE
No entry for configuration.nix in section 5 of the manual

### ISSUE THREAD

**Issue by Pablo1107** [LnL7/nix-darwin#480] opened 2022-07-23 05:26 UTC
When running

```bash
man 5 configuration.nix
```

Probably an error with my flake configuration since I also use home-manager, but I find it hard to debug how the `$MANPATH` is set up.

Some info, `which man` and `which manpath` points to `/usr/bin` which idk if that should be the case. And `echo $MANPATH` is missing `/run/current-system/sw/share/man`, should I add this to the `$MANPATH` by myself?

**Comment by brendanzab** [comment] 2022-08-22 08:46
Do you have the following in your configuration?

```
documentation.enable = true;
```

This will [enable the manpages](https://daiderd.com/nix-darwin/manual/index.html#opt-documentation.enable) for nix-darwin and the system packages, and enable the man package.

**Comment by Pablo1107** [comment] 2022-08-26 12:37
> Do you have the following in your configuration?
> 
> ```nix
> {
>   documentation.enable = true;
> }
> ```
> 
> This will [enable the manpages](https://daiderd.com/nix-darwin/manual/index.html#opt-documentation.enable) for nix-darwin and the system packages, and enable the man package.

Yes, I do have that option enabled, but I don't think the environment variables are correctly set in my shell.

**Comment by lockejan** [comment] 2022-08-28 20:04
What's the actual error?

**Comment by Pablo1107** [comment] 2022-09-03 00:36
> What's the actual error?

No error, the message is the title of this issue. `man` does not seems to find any `nix-darwin` manpages.

**Comment by lockejan** [comment] 2022-09-03 07:19
> Some info, `which man` and `which manpath` points to `/usr/bin` which idk if that should be the case. And `echo $MANPATH` is missing `/run/current-system/sw/share/man`, should I add this to the `$MANPATH` by myself?

nix-darwin doesn't set the MANPATH per default and you shouldn't have to do it either.
The same goes for documentation.enable, because true is the default.

However, in my case I get the man bin from my nix-profile.
`darwin-option documentation.enable` and `darwin-option programs.man.enable` both report true as a current val?

Can you run `darwin-help`? This should open the manpage in your browser.

**Comment by Pablo1107** [comment] 2022-09-04 01:02
> > Some info, `which man` and `which manpath` points to `/usr/bin` which idk if that should be the case. And `echo $MANPATH` is missing `/run/current-system/sw/share/man`, should I add this to the `$MANPATH` by myself?
> 
> nix-darwin doesn't set the MANPATH per default and you shouldn't have to do it either. The same goes for documentation.enable, because true is the default.
> 
> However, in my case I get the man bin from my nix-profile. `darwin-option documentation.enable` and `darwin-option programs.man.enable` both report true as a current val?
> 
> Can you run `darwin-help`? This should open the manpage in your browser.

`darwin-option` does not work, because I configure nix darwin via flakes. `darwin-help` does work, but I lack all the nix-darwin installed man pages. Also, as I pointed out in the OP, `which man` outputs `/usr/bin/man` which I supposed is the culprit. Maybe that should point to a nix man instead, but the order in the path prioritizes `/usr/bin` over nix binaries which idk if that should be like that or not, again, noobie question.

**Comment by Enzime** [comment] 2023-08-05 22:20
Are you still running into this issue? I believe `man` should determine the `MANPATH` variable from the `PATH` variable, so you shouldn't have `MANPATH` set in your terminal.

**Comment by Pablo1107** [comment] 2023-08-06 05:54
I actually don't have a MacBook anymore so I cannot test. If nobody can reproduce, we can close this.

**Comment by Enzime** [comment] 2023-08-06 06:13
I'll close this for now, if anyone else can reproduce this, feel free to leave a comment :+1:

**Closed by Enzime** 2023-08-06 06:13 UTC
