### ISSUE TITLE
Unnecessary NIX_PATH entry causing warnings in Single User installation

### ISSUE THREAD

**Issue by oceanlewis** [LnL7/nix-darwin#295] opened 2021-02-19 22:08 UTC
Referencing: https://github.com/NixOS/nix/issues/2982

Exact line in question: https://github.com/LnL7/nix-darwin/blob/5c3146b75d5d478f0693d0ea6c83f1da8382ff56/pkgs/darwin-installer/default.nix#L15

It looks like whenever I run nix-darwin commands (or any nix command since adopting nix-darwin), I get a warning similar to the following:

```
➜ nix-channel --update
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
these derivations will be built:
  /nix/store/5spmnfl25djn5dwxahxgrk3m5gzxsnwp-home-manager.drv
building '/nix/store/5spmnfl25djn5dwxahxgrk3m5gzxsnwp-home-manager.drv'...
unpacking channels...
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
created 3 symlinks in user environment
```

Checking out my $NIX_PATH there's an extra entry in here referencing a directory I don't have as I'm (guessing here) using an Single User installation of NixPkgs.

```
➜ echo $NIX_PATH
darwin-config=/Users/david/.config/nixpkgs/system/darwin/configuration.nix:/nix/var/nix/profiles/per-user/root/channels:/Users/david/.nix-defexpr/channels:/Users/david/.nix-defexpr/channels
```

I'm not sure if there's a way to check if NixPkgs is running as single or multi-user, but it makes sense to me that nix-darwin should check which one the user has going and conditionally include this extra `'/nix/var/nix/profiles/per-user/root/channels'` when the installation is a multi-user one and not for single-user installations.

Just to be clear, this isn't breaking anything as far as I can tell, it's just an eyesore and hopefully an easy fix 🙂

**Comment by cpick** [comment] 2024-11-25 23:13
See also: https://github.com/LnL7/nix-darwin/issues/145

**Comment by Enzime** [comment] 2024-11-25 23:17
Closing this as a duplicate of #145

**Closed by Enzime** 2024-11-25 23:17 UTC
