### ISSUE TITLE
`activationScripts.applications` creates ~/Application at root home directory

### ISSUE THREAD

**Issue by fanzeyi** [LnL7/nix-darwin#268] opened 2021-01-07 07:36 UTC
Hi, a noob question (I just started to set up this today). I saw `nix-darwin` would try to set up a symlink at `~/Applications` but it seems the link wasn't created even when I made sure there is no `~/Applications` in my home directory. After some digging it seems nix-darwin is executing that particular script as root (since it's a part of `activationScripts.script` instead of `activationScripts.userScript`, so `~/Applications` is resolved to `/var/run/root/Applications`.

Maybe we should move this step to the user activation script?

https://github.com/LnL7/nix-darwin/blob/1804b8ecd2dcd822fdd6185aeb84fb4c2a5064c6/modules/system/activation-scripts.nix#L58

**Comment by kubukoz** [comment] 2021-01-31 05:31
Interesting, in my case this was running as the right user apparently, because nix-darwin created its own Applications in my home directory. I have a single-user Nix install though.

**Comment by winterqt** [comment] 2021-07-27 23:00
@fanzeyi How are you running `darwin-rebuild`? (i.e. with `sudo` or without, etc.)

I ask this since this works as intended on my machine, even though the script is ran as `sudo`. As far as I know, this is due to the differences between the effective and real user ID, and how the shell expands `~`.

**Comment by fanzeyi** [comment] 2021-07-28 17:01
Hi, sorry I can't recall clearly if I ran `darwin-rebuild` with `sudo` or not. It's a good point since normally it can't get root privileges without sudo. IIRC I initialed the command without sudo but in the process it asks me for root password.

Note my laptop is somewhat configured with enterprise profile and I think they enabled the root user in someway that is a little different than the default macOS setting.

**Comment by winterqt** [comment] 2021-07-28 22:48
I can't reproduce this while running just `darwin-rebuild switch`. I believe the only way you can make this behavior you're experiencing happen is if the system activation script was ran with `sudo -i`, which it isn't.

Can you run `sudo bash -c "cd ~; pwd"`, and then for good measure, `sudo -i bash -c "cd ~; pwd"`?

**Comment by Enzime** [comment] 2024-11-07 05:09
Closing this issue as applications should be installed in `/Applications` since #470

**Closed by Enzime** 2024-11-07 05:09 UTC
